### ISSUE TITLE
processContent alternative

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#981] opened 2020-10-22 05:56 UTC
# 🙋 Feature Request
Provide an a way to modify custom element content before everything else

## 🤔 Expected Behavior
Should work similar to `processContent` in AU1

## 😯 Current Behavior
Could not find such feature

## 🔦 Context
Sometimes it's useful to rearrange custom element content before is is processed. E.g. move different parts of the DOM to designated places. Another example is replacing `mdc-row` and `mdc-cell` tags with `tr` and `td` inside an `mdc-table` component

## 💻 Examples
```html
  <mdc-data-table>
    <mdc-data-table-header>
      <mdc-data-table-header-cell>Dessert</mdc-data-table-header-cell>
    </mdc-data-table-header>
    <mdc-data-table-content>
      <mdc-data-table-row repeat.for="dessert of desserts">
        <mdc-data-table-cell>${dessert.name}</mdc-data-table-cell>
      </mdc-data-table-row>
    </mdc-data-table-content>
  </table>
</mdc-data-table>
```
would get transformed into 
```html
<mdc-data-table>
  <table>
    <thead class="...">
      <th class="...">Dessert</th>
    </thead>
    <tbody class="...">
      <tr class="..." repeat.for="dessert of desserts">
        <td class="...">${dessert.name}</td>
      </tr>
    </tbody>
  </table>
</mdc-data-table>
```

**Comment by MaximBalaganskiy** [comment] 2020-10-22 05:57
@fkleuver I was advised you can shed some light on this feature

**Comment by bigopon** [comment] 2020-10-22 08:43
At the moment, this can be done via hooking into `define` lifecycle, and modify the content. Though it's missing:
- an official API
- a way to declare no compilation (return false in `@processContent`)

**Comment by fkleuver** [comment] 2020-10-27 12:57
Yep, this is work in progress and will be added before alpha.

**Comment by Sayan751** [comment] 2020-11-11 19:11
I think this is a duplicate of #667.

**Closed** 2021-01-12 11:07 UTC
Labels: Topic: Templating

**Comment by Sayan751** [comment] 2021-01-12 15:13
During the course of development, the signature of the hook has been changed. Refer the [docs](https://docs.aurelia.io/app-basics/components-revisited#the-processcontent-hook) for details.
