### ISSUE TITLE
Router: Multiple au-viewport elements break app

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1346] opened 2022-01-21 01:57 UTC
I have no idea what causes this error, but in v1 a valid use case was having multiple au-viewport elements, as long as you have unique names for them. This allows you to have viewports you can target and perform different routing operations on.

To see this error, to to the provided repository app and uncomment the viewport element inside of `my-app.html`

**Comment by Sayan751** [comment] 2022-04-16 18:00
This can be closed once the PR #1387 is merged. Cannot reproduce this issue with that version any longer.

**Closed** 2022-04-19 03:51 UTC
Labels: Bug
