### ISSUE TITLE
@aurelia/router-lite Failing to resolve context in Custom Elements - Child app routes

### ISSUE THREAD

**Issue by CollinHerber** [aurelia/aurelia#1740] opened 2023-04-12 23:48 UTC
# 🐛 Bug Report

When you have a custom element, within a child application and a child route within the child application the context fails to properly resolve in Router.load function, even explicitly setting a IRouteContext it still fails.

## 🤔 Expected Behavior

You should be routed correctly to the child route.

## 😯 Current Behavior

The URL is changed to the base url and you are not routed. 

## 💁 Possible Solution

*shrug*

## 🔦 Context

Check out the SB link below for more information

## 💻 Code Sample

https://stackblitz.com/edit/node-asnhvh?file=index.js

Hit "Load Guild" 
Then hit "Support Tickets" in the drawer.
Click "View" on any row

Notice that the route goes blank, and you are not routed.

**UPDATED**

It appears that private repos do not pull automatically, makes sense.  In order to make your own SB you will need access to my private repo. I've sent invites to the following people
* Brandon S
* bigopon
* Sayan
If anyone else wants it, just lmks.

After accepting invite
https://stackblitz.com/ -> click "Nodejs (blank project)"
Click "Connect Repository" in the top left.
Import an existing repository 
Then paste https://github.com/Betsy-Bot/betsy-help
You will need to manually run `npm i` and then `npm run start`
But it should work then

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | dev
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by Sayan751** [comment] 2023-04-13 16:54
It seems that incorrect injection symbol `Router` is used. `IRouter` needs to be used instead.

**Comment by Sayan751** [comment] 2023-04-13 18:52
Closing this, as this is not a bug.

**Comment by brandonseydel** [comment] 2023-04-13 21:41
@CollinHerber after you replaced IRouter everywhere throughout your app you were still required to pass the IRouteContext in instead of this?

**Comment by bigopon** [comment] 2023-04-14 00:10
> It seems that incorrect injection symbol `Router` is used. `IRouter` needs to be used instead.

It seems not uncommon that people are injecting the implementation. Maybe they should also register an alias to make it less error prone. With an option dev message warning

**Comment by Sayan751** [comment] 2023-04-14 06:32
> > It seems that incorrect injection symbol `Router` is used. `IRouter` needs to be used instead.
> 
> It seems not uncommon that people are injecting the implementation. Maybe they should also register an alias to make it less error prone. With an option dev message warning

I think this can be arranged.

**Closed** 2023-04-15 13:54 UTC
