### ISSUE TITLE
Router failed to load any goto page with dash in name.

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#829] opened 2020-03-30 00:08 UTC
# 🐛 Bug Report

I tried to fix our router skeleton by changing the components name to two words with a dash.
This is needed to support Shadow DOM (requires tag name to include at least one dash).
https://github.com/aurelia/new/commit/be52cf12fc490eeffa98d3b1a7952842bd8952fd

## 🤔 Expected Behavior

I expect the router continue to work.

## 😯 Current Behavior

But it failed. I cannot click any link bound to goto.
<img width="722" alt="Screen Shot 2020-03-30 at 11 06 43 am" src="https://user-images.githubusercontent.com/1188806/77864809-95040f00-7276-11ea-8527-38030bca933d.png">

This is not bundler related. I can reproduce it in webpack and dumber.
https://github.com/3cp/au2-router-bug-with-webpack
https://github.com/3cp/au2-router-bug

## 💁 Possible Solution

No idea what's going on.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by jwx** [comment] 2020-03-30 12:05
This not related to routing to components with dashes in their name, but instead seems to be about shadow DOM:
![image](https://user-images.githubusercontent.com/3307996/77910302-3a2ae180-728f-11ea-932f-e0bc734c71d4.png)
@3cp @EisenbergEffect @fkleuver

**Comment by 3cp** [comment] 2020-03-30 12:19
This at least tells us that we should have few more router app e2e setups against shadow dom, and css-module. :-)

**Comment by fkleuver** [comment] 2020-03-31 20:16
> This at least tells us that we should have few more router app e2e setups against shadow dom, and css-module. :-)

We already knew that :-p
Router needs a few thousand more tests. Working on it

**Comment by 3cp** [comment] 2020-06-12 03:38
Probably need to fix this before alpha release. ShadowDOM doesn't work with router at all.

**Comment by Vheissu** [comment] 2020-06-18 05:50
I have encountered a similar issue with the router and Shadow DOM components. For me, they do not appear to be completely broken.

![image](https://user-images.githubusercontent.com/368330/84982987-28185b00-b17b-11ea-91f2-deb7658cee85.png)

**To reproduce the above error, try the following:**

1. Visit https://vheissu.github.io/au-cardigan-ui/dist/#/home (works)
2. Click the buttons nav link to load the buttons route (works, this route has Shadow DOM components inside of it)
3. Refresh the page on the buttons route (you'll get the error above)

The issue appears to be if there first routed component contains Shadow DOM components. In the case of my linked app, the home route has no Shadow DOM components, but the buttons route does.

**Comment by fkleuver** [comment] 2020-12-22 10:56
This was actually fixed a while ago, so closing it

**Closed by fkleuver** 2020-12-22 10:56 UTC
Labels: Topic: Router
