### ISSUE TITLE
@children decorator [RFC]

### ISSUE THREAD

**Issue by davismj** [aurelia/aurelia#331] opened 2018-12-04 02:17 UTC
# 💬 RFC

`@children` should be expanded in the following ways:

1. It should be able to access child view models at various depths and selectors.
2. It should be accessible outside of a decorator.

## 🔦 Context

In vCurrent, I have found `@children` to be the best and only way to solve complex component use cases. Furthermore, this is the only use I have found for it. 

Let's say we have a component `<pane>` that collapses and expands based on its content.

Let's also say we have a component `<accordion>` that has several `<pane>`s. When one `<pane>` opens, whether it is through a click or through a programmatic call to `PaneCustomElement.open()`, all the other `<pane>`s in the `<accordion>` close. It is `<accordion>`'s job to close the other `<pane>`s. To do this, `<accordion>` needs a reference to all of the child `<pane>`s that were added to its slot. 

Note that a `<pane>` can live outside of an `<accordion>`, in which case it is independent of any other `<pane>`.

```html
<accordion>
  <pane id="1"></pane>
  <div>
    <pane id="2"></pane>
  </div>
  <pane id="3">
    <pane id="4"></pane>
  </pane>
  <another-custom-element>
    <pane id="5"></pane>
  </another-custom-element>
</accordion>
```

Right now, the best way to solve this problem is through `@children('pane')`. However, this requires that all `<pane>` elements are direct children of `<accordion>`. In the example above, `<accordion>` can only find out about the view-model for pane#2 by manually looking through the DOM on `attached()` and accessing the private `element.au.controller.viewModel` API. This is hacky solution and in practice I've always let Aurelia force me into a particular DOM structure.

Since the above has been in my experience the most common use case, I think it would be best if `@children('pane')` in `AccordionCustomElement` would access pane#1, pane#2, pane#3. Since we may or may not want to access pane#4 and pane#5, we need some method of supporting those cases on request.

## Other Solutions

**Children.of**

Add a new DI resolver function `Children`, which hoists a newly instantiated dependency to its parent container, up to a configurable depth.

```
@inject(Children.of(PaneCustomElement))
@inject(Children.of(PaneCustomElement), depth = 1)
```

## 💻 Examples

```
<parent-element>
  <child-element id="1"></child-element>
  <div>
    <child-element id="2"></child-element>
  </div>
  <child-element id="3">
    <child-element id="4"></child-element>
  </child-element>
</parent element>
```

`@children('child-element')` on the parent custom element should get a reference to elements 1, 2, 3, and not 4.

**Comment by fkleuver** [comment] 2018-12-04 02:53
I agree 100%. Just took a look at the implementation and I've got some thoughts for implementing this:
- Add an additional boolean argument `subtree` to the decorator. This would tell the `ChildrenObserver` to pass that option to the underlying mutation observer. So when you don't need the subtree, you won't suffer the performance hit of observing recursively
- Keep track of slot nesting depth during rendering. Add a `slotDepth` property to `CustomElement`, which is incremented by 1 whenever a custom element with `@useShadowDOM` is seen.
- On the `childrenChanged` event (if `subtree` is specified), create a `TreeWalker` to walk the elements to find all custom elements in the DOM tree. Only store the ones with 1 slotDepth higher than the element holding the observer.

**Comment by EisenbergEffect** [comment] 2018-12-04 06:18
I'm not sure I agree with this. This makes children not really mean children as it would grab elements which are not the direct child node of the parent. Simply adding subtree to the mutation observer will make it capture *all* elements all the way down the tree, so that forces the complexity of tracking depth. I'm not sure if useShadowDOM would help here at all or if we should have slots involved. To me, the idea was to have an easy way to grab the view models for direct child custom elements. This is effectively what both React and Vue do. So, we'd also be deviating from the norm there as well. I'd be concerned about perf and complexity.

IMO, needs more justification to warrant the increased complexity and perf cost. This also seems more complex when considering additional renderers.

**Comment by davismj** [comment] 2018-12-12 12:16
@EisenbergEffect I've updated with the use case. The important things to note here are (a) this is the only real use case I've had for `@child`/`@children`, and (b) it currently doesn't fully address this use case.

**Comment by EisenbergEffect** [comment] 2018-12-13 01:20
We could do something like adding a depth filter. You'd have to understand that anything above depth one would incur an extra perf cost due to more complex mutation observer work by the browser.

But if you want to get some things at depth X and not other things at the same depth, that seems like it should be handled by the custom element developer. For example above you are saying that you want the children of the `div` but not of the `child-element`. They are both at the same depth, so why one and not the other? It seems complicated to solve this generically and in a performant way.

An updated proposal would be that accessing a `$children` property on the component would get you a live list of the direct children. No special setup needed by the dev. Just access the property if you want that. This aligns with what Vue and React do as well, so there's familiarity and simplicity together. If you want more than direct children, you would add a `@children` decorator and supply some options, such as depth and a filter function. That should handle the above scenarios.

**Comment by EisenbergEffect** [comment] 2018-12-13 01:22
Note that doing with with dependency injection is not the best choice since the children don't exist at the time that injection would need to occur. We'd have to inject something that you couldn't actually access until after a certain point in time. That kind of rubs me the wrong way.

**Comment by davismj** [comment] 2018-12-13 11:31
> Note that doing this with dependency injection is not the best choice since the children don't exist at the time that injection would need to occur.

I agree. Whose stupid idea was that, anyway? :wink:

Kidding aside, even though I agree, I just wanted to include it in case I was wrong.

> We should strive for lower learning curve and better familiarity with other frameworks.

Agreed. We should only be looking to them where they are outdoing us.

> But if you want to get some things at depth X and not other things at the same depth, that seems like it should be handled by the custom element developer. 

Definitely agreed there. But this is the problem in vCurrent. There isn't a good solution for this.

Perhaps a third solution would be to provide two separate tools that can be joined to solve this problem more efficiently. The first would be element.ref / inject(Element), and the second would be some kind of `getModelFor()` function that is little more than a lookup on a private WeakMap that associates Elements with their underlying Component, in order to replace the existing

`Array.from(element.querySelector('something')).map((element) => element.au.controller.viewModel);`

In any case, I would say this is a real use case we want to have a happy path for in vNext. If my proposals are not workable, let's keep this in mind and try to come up with a better way.

**Comment by fkleuver** [comment] 2018-12-13 11:52
> The first would be element.ref / inject(Element)

> lookup on a private WeakMap that associates Elements with their underlying Component

This isn't necessary because we're already storing the viewModel instances on the DOM element instances via a property `$customElement`.

So doing `Array.from(element.querySelectorAll('my-custom-element')).map(ce => ce.$customElement)` would give you a list of all view model instances underneath the element.
The problem is just that: it gives you *all* view model instances, not just those limited to a particular level. It also doesn't provide observation which I think is key here.

My idea with the projectors (again, *if* it works) would be ideal both in terms of performance (no mutation observer is needed, the framework being aware of all mounting/unmounting *is* the observation) and scope limiting (if a custom element is nested within another, then so is its projector, which provides an encapsulation boundary for free).

Going deeper than 1 level could also be provided as an opt-in because if projectors keep references to the parent projectors, they can also simply traverse upwards. This would follow a similar approach to what I did with scope boundary traversal for `replaceable`, except with a masked flag with 8 bits for example, similar to the `ancestor` property in the AST so that it can go up to 511 level deep or whatever seems like a reasonable limit

**Comment by davismj** [comment] 2018-12-13 11:55
> This isn't necessary because we're already storing the viewModel instances on the DOM element instances via a property $customElement.

So, basically `au.controller.viewModel === $customElement`? Will this anger 👿 TypeScript ? I'd rather not anger 👿 TypeScript.

**Comment by fkleuver** [comment] 2018-12-13 12:06
Nah, we have an official API for this now: `CustomElementResource.behaviorFor`

So that would be:

```ts
Array.from(element.querySelectorAll('my-custom-element')).map(ce => CustomElementResource.behaviorFor(ce));
```
Which does exactly that (except it also guards against undefined and always returns null if there is no behavior on the element)

There is also an interface you could cast a node to:

```ts
export interface ICustomElementHost extends IRenderLocation {
  $customElement?: ICustomElement;
}
```

But you shouldn't have to because of the api.

**Comment by davismj** [comment] 2018-12-13 12:12
In that case for now I'll let you and Rob hash out the ROI of the feature, but I think this will yield the power we need.

```typescript
const panes = Array.from(element.querySelectorAll('pane'))
  .filter((pane) => pane.closest('accordion') !== element)
  .map((pane) =>CustomElementResource.behaviorFor(ce));
```

Close when ready.

**Comment by fkleuver** [comment] 2018-12-13 22:35
> Have a $children property that enables the basic scenario of having a live list of immediate children

I still think it should be an opt-in, just like (which is still a todo btw) the `$odd`, `$even` etc properties for the repeater. It's an important use case but still a niche one that I don't think warrants having a redundant property defined on every single view model. That's just CPU and memory pressure for nothing.

> It also enables HTML-only elements to bind against children without needing to create a dummy class just for this feature.

It could be declared as an attribute on the surrogate template element, just like bindables

> Support a @children decorator that allows the developer to customize this behavior by supplying something like a depth and maybe a filt

Agreed

> Support some utility methods as described above to ensure that the most common filter scenarios are really easy for the developer to implement.

I think being able to pass a `{ querySelectorAll: 'my-element' }` or something would do the trick here?

> Obviously, tests

Obviously :)

> those are mostly concerned with projecting the view of the element into the shadow DOM

They are also concerned with instantiating the mutation observers for the ChildrenObserver. ChildrenObserver calls the projector with a callback. So they are in fact already coupled like this, for this very purpose. You built it that way.

The thing with the projectors is that only the `ShadowDOMProjector` actually instantiates a mutation observer and in the other cases it's a no-op. Maybe you're mixing it up with that.

However, the 3 projectors we have are 100% responsible for all mounting and unmounting of custom elements, not just ShadowDOM. 

So since the projector simply takes a callback that it invokes when the children change, instead of doing that via a mutation observer, we could just as well store the callback and simply invoke that callback on every mount and unmount operation. Voila!
It will perform much better and react much faster as well. No mutation observer needed at all. And the scenario described by @davismj comes for free because the projector is only bounded by other projectors and does not care how deeply nested its child custom elements are. I only see wins.

**Comment by EisenbergEffect** [comment] 2018-12-13 22:49
I'm fine with opting in with a decorator if it's easy enough to support it for HTML-only mode with a simple attribute on the template. I hadn't thought of that but it makes sense and you are right, we've got precedent for that for bindables.

In terms of the projectors, I remember now that they had the responsibility of setting up the child observer. It's just that the only case where that's needed is when there are actually children and a view, which is when shadow dom is required. However, I don't think it's as simple as invoking the callback on mount and unmount. If the children contain an if, repeat, compose or anything similiar and in any combination that dynamically changes the children at any level, then those changes would need to be live reflected to the children property. It's not a one-time mount/ummount operation. The classic example from the early days of vCurrent for this is the tab control where you want to use bindings to repeater.for and generate the tab headers based on the child element tab items, and you want to be able to dynamically add/remove tab items based on data. Here's some old sample code of mine.

**tab-control.html**
```xml
<template>
  <ul class="nav nav-tabs">
    <li repeat.for="item of items" class="${item.isSelected ? 'active' : ''}">
      <a href="#" click.trigger="$parent.selectItem(item)">${item.title}</a>
    </li>
  </ul>

  <slot></slot>
</template>
```

**tab-control.js**
```js
import {children} from 'aurelia-framework';

export class TabControl {
  @children('tab-item') items = [];
  selectedItem = null;

  itemsChanged(mutations){
    if(this.items.length > 0){
      if(!this.selectedItem || this.items.indexOf(this.selectedItem) === -1){
        this.selectItem(this.items[0]);
      }
    }
  }

  selectItem(item){
    if(this.selectedItem){
      this.selectedItem.isSelected = false;
    }

    this.selectedItem = item;

    if(this.selectedItem){
      this.selectedItem.isSelected = true;
    }
  }
}
```

**tab-item.html**
```xml
<template>
  <div class="tab-pane" show.bind="isSelected">
    <h2 replaceable part="title">${title}</h2>
    <slot></slot>
  </div>
</template>
```

**tab-item.js**
```js
import {bindable} from 'aurelia-framework';

export class TabItem {
  @bindable title;

  constructor(){
    this.isSelected = false;
  }
}
```

**Comment by fkleuver** [comment] 2018-12-13 23:34
> I don't think it's as simple as invoking the callback on mount and unmount.

Of course there is more to it. I hadn't given the implementation details much thought and was just flapping out what came to mind.

My point is that we have the information, as well as the infrastructure to efficiently pass that information up and down on the component tree via the attach/detach lifecycles. A modified ordering of elements can cleanly be derived from that because:
1) We know when elements (and their parents/children) are added to the DOM
2) We know when they're removed from the DOM
3) We know the order in which they exist in the DOM

Perhaps the projectors shouldn't have the responsibility of observing and just stick to mount/unmount. Perhaps we can have `ConnectionTracker` (as in, tracks connected/disconnected per the web component definition) and the projector tells it when something mounts/unmounts. Then if we need just a little bit of extra cleverness to properly derive the new state/ordering of the children array, it has a proper place.

Regarding point 3, all `$attachables` are in a doubly linked list whose `$prevAttach` and `$nextAttach` can be used to determine a positional change of an element in an array, and reflect that change on the property tracking them.

Matter of fact, why even bother with a callback when we can let the projector/tracker/whatever just modify the array and let an array observer take care of the change notifications and such.

**Comment by EisenbergEffect** [comment] 2018-12-13 23:48
It still seems pretty non-trivial to handle it that way. So, I'd want to make sure it wasn't introducing a ton of code and complexity and that it definitely performed better than just setting up a mutation observer. I'm always open to new ways of doing things.

**Comment by bigopon** [comment] 2018-12-14 00:08
I'd add another case for the evaluation of this feature: a menu and submenu like following block:
```html
  <menu-list id="root-menu">
    <h1>Menu header</h1>
    <menu-list-item>Hello 1</menu-list-item>
	  <menu-list-item>Hello 2</menu-list-item>
    <menu-list-item>Hello 3</menu-list-item>
    <menu-list-item>
      <menu-list>
        <h2>Header 2</h2>
        <menu-list-item>Hello 4.1</menu-list-item>
        <menu-list-item>Hello 4.2</menu-list-item>
      </menu-list>
    </menu-list-item>
    <menu-list-item>Hello 5</menu-list-item>
  </menu-list>
```
Root `<menu-list/>` will want to know all sub `<menu-list/>` so it can manage focus/ blur states and more. Example from @tonylugg

**Comment by fkleuver** [comment] 2018-12-14 00:15
`@descendants` for that? ;)

**Comment by TonyLugg** [comment] 2018-12-14 13:45
It is a multi-level popup-menu that will have submenu's absolute positioned near their parent based on viewport position and size.  I need to built a typescript code representation of the tree represented by the HTML structure of custom elements.  My custom elements need to know if the parent is currently visible, etc.  My challenge has been getting hold of the view models of the custom elements.  This thread has given me some things to try regarding that, so I will do so.

**Comment by TonyLugg** [comment] 2018-12-20 14:21
My TypeScript doesn't find CustomElementResource.  Is there something I have to import?

**Comment by fkleuver** [comment] 2018-12-20 16:13
@TonyLugg It's a vNext feature. I hope you're not building something with this yet? :p

**Comment by fkleuver** [comment] 2018-12-20 16:40
Haha :) Yeah, `au.controller.viewModel` is generally the way to do it in vCurrent. If you want the code to be a little robust you'll want to have a function like this:

```
export function getViewModel(el) {
    return el && el.au && el.au.controller && el.au.controller.viewModel || null;
}
```

**Comment by TonyLugg** [comment] 2018-12-20 21:08
TypeScript doesn't like it. :(

**Comment by fkleuver** [comment] 2018-12-20 21:12
Yeah, that's another thing we'll fix in vNext. But TypeScript needs to shut up in this case :)

This ought to do the trick:

```ts
export function getViewModel<T = unknown>(el: Element & { au?: { controller?: { viewModel?: T } } } ): T | null {
    return el && el.au && el.au.controller && el.au.controller.viewModel || null;
}
```

**Comment by TonyLugg** [comment] 2018-12-20 22:03
@children seems to only work in Chrome.  I've tested with Edge and FF, but only Chrome works...

**Comment by fkleuver** [comment] 2018-12-20 22:30
That's because Shadow DOM is only implemented in Chrome at the moment. And for reasons unknown to me `@children` only applies to Shadow DOM (another thing which is going to change in vNext).
@EisenbergEffect surely this can't be intentional?

**Comment by TonyLugg** [comment] 2018-12-20 22:34
Hmm, that makes @children somewhat useless at present.  The docs don't mention this.  I had actually made really good progress building a linked list tree structure and was horrified to find it only worked in Chrome.

**Comment by fkleuver** [comment] 2018-12-20 23:13
I'm not 100% sure, I haven't checked the vCurrent code around this yet. But that's how @EisenbergEffect 
 initially implemented it in vNext at least. In any case, have you tried using `@useShadowDOM` on your custom element?

**Comment by StrahilKazlachev** [comment] 2018-12-20 23:14
I'm a bit confused, in *vCurrent* `@children` should work regardless of shadow DOM, as far as immediate children are concerned.
Also from the docs for `@children`:
> element's immediate child content

So if this is not the case could someone open an issue in *templating*?

**Comment by fkleuver** [comment] 2018-12-20 23:16
> should work regardless of shadow DOM,

Agreed, this is just how @EisenbergEffect implemented it in vNext at first. Well, we commented at the same time so you didn't see my previous remark about this yet :)

> So if this is not the case could someone open an issue in templating?

If what is not the case? Not immediate child content, or not the child content of anything except for a shadow DOM element?

**Comment by StrahilKazlachev** [comment] 2018-12-20 23:20
> If what is not the case? Not immediate child content, or not the child content of anything except for a shadow DOM element?

To open an issue if it does *not* detect mutations for immediate children.

**Comment by TonyLugg** [comment] 2018-12-20 23:20
@StrahilKazlachev It does returning the element's immediate child content, but only in Chrome.

**Comment by TonyLugg** [comment] 2018-12-20 23:31
@fkleuver It is working in FF actually, but not in Edge.

**Comment by fkleuver** [comment] 2018-12-20 23:36
@TonyLugg Can you pretty please open an issue in templating then? I'd want to ask more details about your implementation to help you out (since it works for me in Edge), but not here, because this is going to make it very tedious for future readers and discussions regarding the vNext implementation to quickly get the information they're looking for.

**Comment by davismj** [comment] 2018-12-22 03:05
@fkleuver I actually appreciate `@descendants(depth = 1)`. In favor of changing that, and _maybe_ providing `@children` as an alias to `@descendants`. 

> I'm fine with opting in with a decorator if it's easy enough to support it for HTML-only mode with a simple attribute on the template. 

@EisenbergEffect I think this is an anti-practice, personally. A "dummy class" can be extremely short, and I don't think we're complicating the API significantly by forcing people to create a class. On the other hand, I think giving too many features in HTML-only encourages developers to use HTML-only because they can and not because it's the right design choice.

> The classic example from the early days of vCurrent for this is the tab control where you want to use bindings to repeater.for and generate the tab headers based on the child element tab items, and you want to be able to dynamically add/remove tab items based on data. Here's some old sample code of mine.

Yep, this is the perfect example which can't be solved with just the imperative approach. There are other similar cases to this in which case you might want to nest the "tab-item" element in another element, and thus the need for depth. 

> TypeScript doesn't like it. :(

@TonyLugg this is how I typically do it.

```typescript
const viewModels = Array.from(this.element.querySelectorAll('element')
  .map((el: any) => el.au.controller.viewModel)
```

If you can create a simple repro and open an issue, we'll get it fixed. Otherwise, it might be another issue locally, and if you need help please reach out.

**Comment by EisenbergEffect** [comment] 2018-12-22 03:44
I don't see why HTML-only components would be an anti-practice. If your component has no logic at all, then adding an empty class file seems like adding a maintenance burden. HTML-only components are unique to Aurelia compared to other frameworks and we've had various requests to give them more attention over the years. This seems like a simple improvement to make.

On the decorator naming side, if we can keep `children` and just add a `depth` property then that adds backwards compat. It might even be possible to port that back to vCurrent. If you feel strongly that `descendants` is better than we'd need to provide a `children` decorator in a compat-module at least. So far we've maintained a lot of compatibility in the actual html syntax and decorators, so I'd want to see what we can reasonably preserve in this case as well.

@davismj See aurelia/templating#655 We've got a repro now.

**Comment by davismj** [comment] 2018-12-22 03:50
> I don't see why HTML-only components would be an anti-practice. If your component has no logic at all, then adding an empty class file seems like adding a maintenance burden. 

Agreed. "no logic at all" is where I would draw the line. If you need logic, I recommend making a class. My assumption here is that if you need to leverage `@children`, your component has logic. Am I wrong?

> I'd want to see what we can reasonably preserve in this case as well.

Definitely agreed. I'd like to hear other opinions too. Personally, `@descendants` is a clearer name considering the functionality, but I don't feel strongly about it.

**Comment by EisenbergEffect** [comment] 2018-12-22 03:55
There's a set of scenarios where you just need to sort of "re-project" the children into a data structure so that you can bind against it to produce something else in HTML. So, there are things you can do with this that don't require additional logic. It's probably not super common but I'd like to support it.

**Comment by davismj** [comment] 2018-12-22 03:57
Great.

**Comment by fkleuver** [comment] 2018-12-22 17:39
I just realized as I wrote that that using the lifecycle flags for this won't be viable when multiple nested custom elements use child observation as the flags would overlap, so I'll stop talking about this approach until I've actually tried it and got it to work :) anyway, I think it can/should be solved without mutation observers. The problem especially with limiting depth via mutation observers is you then have to track depth in some other way that would be at least equally complex I think.

**Comment by EisenbergEffect** [comment] 2019-08-01 22:56
Closing this now that we've got the new children decorator in :)

**Closed by EisenbergEffect** 2019-08-01 22:56 UTC
