### ISSUE TITLE
Loading images with webpack

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#1123] opened 2021-02-23 22:41 UTC
How do I configure webpack to process `<img src="local_path">`?

**Comment by bigopon** [comment] 2021-02-24 01:16
Thank you for the issue, please do the Q/A on discourse. If you are using this as a way do help document FAQs, please help create a PR for it.

**Comment by MaximBalaganskiy** [comment] 2021-02-24 02:00
Not sure I'm following 😕 
I don't know the answer for this.
In Au1 images were processed by html-loader.
In Au2 html is compiled into js modules and html-loader cannot help with those.

**Comment by 3cp** [comment] 2021-02-25 19:38
I think our webpack loader should support the result of html-loader, so that we can chain them. Let the html-loader process it first, then our loader.
I will get back to you on this.

**Comment by MaximBalaganskiy** [comment] 2021-02-25 20:32
I've tried that - didn't work. Tried chaining both ways

**Comment by 3cp** [comment] 2021-02-25 20:45
I am aware of that. I meant "should add support of ...".

**Comment by 3cp** [comment] 2021-02-26 10:04
Troublesome, not sure how to deal with the output of html-loader.

An example of the output of html-loader.
```js
// Imports
import ___HTML_LOADER_GET_SOURCE_FROM_IMPORT___ from "file:///Users/huocp/playground/my-app/node_modules/html-loader/dist/runtime/getUrl.js";
var ___HTML_LOADER_IMPORT_0___ = new URL("./test.jpg", import.meta.url);
// Module
var ___HTML_LOADER_REPLACEMENT_0___ = ___HTML_LOADER_GET_SOURCE_FROM_IMPORT___(___HTML_LOADER_IMPORT_0___);
var code = "<div class=\"message\">${message}</div>\n<img src=\"" + ___HTML_LOADER_REPLACEMENT_0___ + "\" alt=\"\">\n";
// Exports
export default code;
```

**Comment by MaximBalaganskiy** [comment] 2021-02-26 11:03
May be take html loader as a base and tweak it to produce Aurelia html modules?

**Comment by 3cp** [comment] 2021-02-26 11:34
Thought about similar approach, then we need to expose all html-loader options.

**Comment by MaximBalaganskiy** [comment] 2021-02-26 11:39
I would clone html-loader and made precise "cuts" :) so that any time original changes it is easily transferred

**Comment by Sayan751** [comment] 2021-03-01 20:59
If you are using webpack, then the most stable way would be to import the image in TS/JS using https://webpack.js.org/loaders/url-loader/, and bind the import (depending on the loader configuration it is either b64 encoded data url, or a simple string url) to the `src` of `img`. That way you don't need to perform any gymnastic with the html loader. Copying the images to the configured output location is also taken care of by the loader itself.

**Comment by MaximBalaganskiy** [comment] 2021-03-01 21:02
This is a bit inconvenient, as compared to how everyone else does it.

**Comment by Sayan751** [comment] 2021-03-01 21:36
As at the end the html templates get bundled into the bundle JS file, I should not expect to have similar relative directory structure also in output.
Striving to maintain the relative directory structure also in output seems rather needless IMO, considering there are easier solutions present.

Anyway, IMO this is not a Aurelia-specific issue. @fkleuver @bigopon Can we activate the GH Discussions for community discussions? IMO that way we can better track the issues.

**Comment by DennisDyallo** [comment] 2021-03-05 14:26
Hi! I'm also having this problem :) 
Can you provide a working example of the workaround your describing @Sayan751 ? Thanks

**Comment by 3cp** [comment] 2021-03-06 00:22
I think this issue is more than just `<img>`.

The bottom conflict is that Aurelia 2 needs to preprocess html string because we moved conventions from runtime (Aurelia 1) to compile time (Aurelia 2). We need html to be plain string in order to preprocess it based on static analysis.

But html-loader produces JS code from html. The above output example is still a simple case where we might be able to reason about the final html string. But we cannot assume html-loader only writes html string in this fashion, as it provides many options. It also dangerous to assume the output format of html-loader, as html-loader might adjust the output in future implementation (which is not a breaking change in normal sense, but can break our assumption).

The issue is that it's difficult to try to do static analysis on a string dynamically built from code (which is finalised at runtime).

**Comment by 3cp** [comment] 2021-03-06 00:55
It's difficult to support webpack loader chaining. I think the only practical solution is to wrap html-loader in our loader as @MaximBalaganskiy suggested. It's not pretty and should work. Other suggestions are welcome.

**Comment by Sayan751** [comment] 2021-03-06 13:27
@DennisDyallo Here is a minimalistic example of what I meant. https://github.com/Sayan751/au2-webpack-img-demo

Note that there are 2 images one small and another is large. The images are imported as follows:

https://github.com/Sayan751/au2-webpack-img-demo/blob/d3a3296ace80dbc1756b69dab08637eb78f6a7e9/src/app.ts#L3-L10

And used like this

https://github.com/Sayan751/au2-webpack-img-demo/blob/d3a3296ace80dbc1756b69dab08637eb78f6a7e9/src/app.html#L1-L10

Depending on your webpack config, the images are loaded using the `http:` scheme or the `data:` scheme (for smaller images).

https://github.com/Sayan751/au2-webpack-img-demo/blob/d3a3296ace80dbc1756b69dab08637eb78f6a7e9/webpack.config.js#L30

When you build the app, this is how the output looks like. Note that the larger image name is replaced with webpack-friendly id.

![image](https://user-images.githubusercontent.com/3128881/110208104-801cfc00-7e87-11eb-926d-86b306df477d.png)

**Comment by WisdomCorp** [comment] 2022-01-03 16:31
It seems still there is no solution for this issue? or any workaround? Who has ownership of leading Aurelia project currently?

**Comment by Vheissu** [comment] 2022-09-06 06:19
Is there anything we need to action for this @Sayan751 @3cp ?

**Comment by Sayan751** [comment] 2022-09-06 15:43
@Vheissu I think there are already alternatives present for this and this is nothing specific to do with Aurelia. I think we can close this issue, and if need be, continue the discussion in a GH-Discussions thread.

**Comment by Gryhyphen** [comment] 2023-10-23 05:56
Running into this issue now, switching over from jspm to webpack in Aurelia/v1. Of course, there is going to be friction, but what I'm being told based on the info here is that I cannot configure Aurelia to perform both import and "binding" of the image without updating my code base? (huge opposite of winning for my usecase, it is painful to have to go through every component and import it in the JS and then bind in the html.)

Require tags in html do generate the assets and include them in the dist folder, what does it take to get Aurelia to know to switch the location it's pointing at to include them in output?

**Comment by Sayan751** [comment] 2023-10-23 06:13
@Gryhyphen this issue/discussion is meant for aurelia2. If you are dealing with aurelia1 then please post in the appropriate repository or ask in our discourse chat.

**Closed** 2023-12-28 11:46 UTC
Labels: In discussion, Topic: Conventions, question
