### ISSUE TITLE
au-compose should support slots

### ISSUE THREAD

**Issue by mattduffield** [aurelia/aurelia#591] opened 2019-08-22 23:01 UTC
# 🐛 Bug Report
When using the `au-compose` element, it should be have just like a custom element. 
The idea is that if you put content inside the `au-compose` element and the element that you compose has slots in its view, then the content will get projected into the slot of your composed element. This would give us the same power of any given custom element but being dynamic.

## 🤔 Expected Behavior
`au-compose` elements containing slots should function exactly as if they were statically declared inline, with their binding and content HTML.

## 😯 Current Behavior
Currently, slots are not supported. 

## 🔦 Context
Without this feature, the `au-compose` element will behave differently from standard custom elements. By making them the same, it provides consistency when working with elements.

See #497 for more context.

## 💻 Code Sample
We'd like to be able to write the following:
```html
<au-compose view-model="test">
  <div slot="slot1">
    Custom slot content
  </div>
</au-compose>
```

**Comment by Sayan751** [comment] 2021-05-29 12:37
Removing the label "bug" from this, as this is not a bug.

I am not even sure if we even want to support this. My argument against this would be as follows: au-compose is inherently dynamic in nature. My typical use-case with compose is that I tend to use it as a dynamic view composition factory. For example, we have a grid of controls, where every row is rendered by an instance of compose, and depending on the bound view-model from each row, a different view will be rendered. With such dynamism in mind, attempting a projection to the bound view-model/view seems overly complex to me.

I would like to know if there are any real-life use cases for this.

cc: @bigopon

**Comment by bigopon** [comment] 2021-06-25 08:03
I think compose is about the internal of an element, for either layout or actual functionality purposes, and the content is about how the usage of that element interacts with the internal. For examples, composing a field in a row of a datagrid:

For layout purpose:
```html
<div repeat.for="row of data">
  <div>Label: ${row.name}</div>
  <compose view-model.bind="row.fieldType">
    <input value.bind="row.value">
  </compose>
</div>
```
For functionality switch purposes:
```html
<div repeat.for="row of data">
  <div>Label: ${row.name}</div>
  <compose view-model.bind="getViewModel(row.fieldType)" model.bind="row"></compose>
</div>
```

With shadow DOM, external and internal works seamlessly together, it's how native shadow DOM works.
With au-slot, I think it's possible, maybe even easy, to pass slot information to the custom element being composed, just need to ensure the scope is the parent of compose, instead the compose itself.

**Comment by Vheissu** [comment] 2022-09-06 06:25
I am going to close this issue as the consensus appears to be compose is for the internal of a component.

**Closed by Vheissu** 2022-09-06 06:25 UTC
Labels: Topic: compose, Needs more info, In discussion, Topic: Compiling/rendering
