### ISSUE TITLE
Validation is not triggering when pasting

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1462] opened 2022-06-09 18:40 UTC
# 🐛 Bug Report
When pasting into a field with validation and default trigger of change it does not revalidate the input.

## 🤔 Expected Behavior

Input re-validates.

## 😯 Current Behavior

When pasting into a field with validation and default trigger of change it does not revalidate the input.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by brandonseydel** [comment] 2022-06-09 18:40
@Sayan751 - Is this a bug or something missing?

**Comment by Sayan751** [comment] 2022-06-09 19:55
@brandonseydel Would appreciate a reproduction of the issue. Here is something I tried, in order to reproduce the issue: https://stackblitz.com/edit/au2-validation-gh-issue-1462?file=index.ts,app.ts; but it seems to be working. Feel free to fork in order to reproduce the issue.

**Comment by Alexander-Taran** [comment] 2022-06-09 20:14
might depend on browser and `preventDefault()` from a rogue event handler.
As far as I remember paste triggers input.
https://codepen.io/Alexander-Taran/pen/PoQRwWZ

**Comment by brandonseydel** [comment] 2022-06-09 20:23
@Alexander-Taran @Sayan751 - I am creating this issue for a user that showed me so this could be.

**Comment by Sayan751** [comment] 2022-06-10 04:25
> @Alexander-Taran @Sayan751 - I am creating this issue for a user that showed me so this could be.

They are free to fork my SB example in order to reproduce the issue.

**Comment by IonelLupu** [comment] 2022-06-10 06:12
hi @Sayan751  @Alexander-Taran  I am the one that found the issue

After investigating the issue even more I found the culprit: the presenter. I created a custom presenter to display the error and, in the add and remove methods, I had something similar to this:

```ts
import { ValidationResultPresenterService } from "@aurelia/validation-html";
import { ValidationResult } from "@aurelia/validation";
import { INode } from "aurelia";

export class MyErrorPresenter extends ValidationResultPresenterService {

  remove(target: INode<HTMLElement>, results: ValidationResult[]) {
    results = results.filter(result => result.valid); // get all the valid fields in order to remove the errors
    if (!results.length) {
      return;
    }

    // remove errors here
  }

  add(target: INode<HTMLElement>, results: ValidationResult[]) {
    results = results.filter(result => !result.valid); // get all the invalid fields in order to show the errors
    if (!results.length) {
      return;
    }

    // show errors here
  }

}

```

I checked [the presenter from aurelia/validation](https://github.com/aurelia/aurelia/blob/master/packages/validation-html/src/subscribers/validation-result-presenter-service.ts) and it seems the condition is different when filtering the results in the `remove` method. In my presenter's `remove` method I added `results = results.filter(result => result.valid);` which returns me all the valid fields, meaning I have to remove the errors FROM the valid fields (because they are valid now and no errors should show up). But in the Aurelia's presenter [the condition](https://github.com/aurelia/aurelia/blob/master/packages/validation-html/src/subscribers/validation-result-presenter-service.ts#L63) is reversed (`if (!result.valid)`) which is a bit confusing because it looks like it removes the error for the invalid fields,. For me doesn't make sense. Why would you remove the errors from the invalid fields. You want to remove the errors from valid fields, right?

I am sure I am missing something.


In any case, I switched to the same condition: "!valid AKA remove errors for invalid fields" and now my presenter works correctly. Still, that condition is confusing 😄

**Comment by Sayan751** [comment] 2022-06-10 06:41
@IonelLupu Note the `ValidationEvent#removedResult` and `ValidationEvent#addedResults`. The whole set of removed errors can be removed safely from DOM and the whole set of added errors can be added to the DOM. This is done to keep the filtering at the presenter at minimum or non-existent, in words to keep the presenter implementation simpler as I feel that that is one thing, devs would like to customize.

I am closing this issue. However, feel free to continue the discussion.

**Closed by Sayan751** 2022-06-10 06:41 UTC

**Comment by IonelLupu** [comment] 2022-06-10 06:53
If they can all be removed, why is `removedResult` having an [if statement there](https://github.com/aurelia/aurelia/blob/master/packages/validation-html/src/subscribers/validation-result-presenter-service.ts#L63). Why no removing all the results? 🤔  I am trying to understand the reasoning. I will be more than happy to remove the if statements from my presenter 😆

**Comment by Sayan751** [comment] 2022-06-11 15:14
> If they can all be removed, why is `removedResult` having an [if statement there](https://github.com/aurelia/aurelia/blob/master/packages/validation-html/src/subscribers/validation-result-presenter-service.ts#L63). Why no removing all the results? 🤔

@IonelLupu You are right. I misspoke slightly. Often when dealing with validation, I end up thinking that only the errors are added to the result-set, which is an incorrect assumption, as the valid results also end up in the result-sets. What I wanted to say is this: 
- You can **add all the invalid** results from the `ValidationEvent#addedResults` to the DOM (as the errors, in this case, are of interest).
- And as you have added only the invalid results from `ValidationEvent#addedResults`, while dealing with  `ValidationEvent#removedResults` you only need to **remove** the one, those **were invalid**. You can ignore the valid ones, as those weren't added to the DOM in the first place.

Very loosely speaking, another way of thinking about this would be: 
- old results → `ValidationEvent#removedResults`
- new results → `ValidationEvent#addedResults`

Coming back to your original question:

> But in the Aurelia's presenter [the condition](https://github.com/aurelia/aurelia/blob/master/packages/validation-html/src/subscribers/validation-result-presenter-service.ts#L63) is reversed (`if (!result.valid)`) which is a bit confusing because it looks like it removes the error for the invalid fields,. For me doesn't make sense. Why would you remove the errors from the invalid fields. You want to remove the errors from valid fields, right?

Aurelia deals with the two sets of results separately. First, it removes the old invalid results, coming from the `ValidationEvent#removedResults`, then it adds the new invalid results, coming from the `ValidationEvent#addedResults`. Any old error, still persisting, is always present in the `ValidationEvent#addedResults`. Hence, all the old invalid results can be safely removed, as any persisting errors will be added down the line. As these two sets of errors are never merged physically, the decision-making process of adding/removing errors becomes trivial.

The presenter service you referred was written as a parallel of the v1's example renderer for bootstrap. This is not one of my favourite as there might be edge cases, depending on the layout of DOM elements, where it might not work. Thus, as an example, this here is a bit easier to deal with as well as understand: https://github.com/aurelia/aurelia/blob/master/packages/validation-html/src/subscribers/validation-container-custom-element.ts.
