### ISSUE TITLE
$index in repeat.for statements returning incorrect values

### ISSUE THREAD

**Issue by tomtomau** [aurelia/aurelia#1788] opened 2023-07-04 07:47 UTC
# 🐛 Bug Report

If there are identical items in an array, using the $index for repeat.for will return the last $index for that value, see reproduction below.

Repro link: https://stackblitz.com/edit/au2-conventions-emggat?file=src%2Fmy-app.ts&file=src%2Fmy-app.html

## 🤔 Expected Behavior

Should have rendered:

```
Index: 0

Message: foo

Index: 1

Message: bar

Index: 2

Message: foo
```

## 😯 Current Behavior

```
Index: 2

Message: foo

Index: 1

Message: bar

Index: 2

Message: foo
```

## 💁 Possible Solution

I'm guessing that `$index` is working by returning the indexOf this item in the collection, or something similar.

## 🔦 Context

n/a

## 💻 Code Sample

Repro link: https://stackblitz.com/edit/au2-conventions-emggat?file=src%2Fmy-app.ts&file=src%2Fmy-app.html

## 🌍 Your Environment

Observed in 2.0.0-beta.7 and 2.0.0-beta.6 but haven't checked further versions.

**Comment by ekzobrain** [comment] 2023-07-15 11:09
Also faced this issue, very important one

**Comment by Alexander-Taran** [comment] 2023-08-01 12:24
@ekzobrain @tomtomau 
Out of curiosity what values your collection holds. Why are there are same values?

**Comment by ekzobrain** [comment] 2023-08-01 13:41
> @ekzobrain @tomtomau 
> 
> Out of curiosity what values your collection holds. Why are there are same values?

The problem is that there is a bug with duplicate values (of any type) in array. In this case all equal values use the same context and thus get the same $index/$last/etc context variables.

**Comment by tomtomau** [comment] 2023-08-02 06:54
@Alexander-Taran in my case I was porting some old Aurelia 1 code which had some less-than-ideal mechanism of looping - I was able to find more favourable ways to iterate over the arrays in Aurelia 2 such that it didn't materially block me.

That said, this feel like a significant issue that needs to be resolved still

**Comment by ekzobrain** [comment] 2023-08-02 09:07
Work is in progress, but the problem is deeper than it might be, so needs some more time to fix.

**Comment by bigopon** [comment] 2023-08-02 22:41
@fkleuver and I are looking at the fix, we will have this regression fixed. Unless you want to tackle it @ekzobrain.

**Comment by bigopon** [comment] 2024-01-25 03:21
This been fixed by a recent PR by @fkleuver . Thanks for the issue!

**Closed by bigopon** 2024-01-25 03:21 UTC
Labels: Bug, Topic: repeat

**Comment by superspartak** [comment] 2024-09-10 08:07
This issue is observed by me again in beta-v19 @bigopon. Any possibility that it is unintentionally undone?
