### ISSUE TITLE
AUR0501 triggered by containerless even when there are no slots used at all

### ISSUE THREAD

**Issue by wzrdtales** [aurelia/aurelia#1823] opened 2023-10-15 22:41 UTC
The following code

```html
<import from="./instance-table-item"></import>
<div
  class="bg-white dark:bg-slate-800 shadow-lg rounded-sm border border-slate-200 dark:border-slate-700 relative"
>
  <header class="px-5 py-4">
    <h2 class="font-semibold text-slate-800 dark:text-slate-100">
      All Orders
      <span class="text-slate-400 dark:text-slate-500 font-medium">442</span>
    </h2>
  </header>
  <div>
    <!-- Table -->
    <div class="overflow-x-auto">
      <table
        class="table-auto w-full dark:text-slate-300 divide-y divide-slate-200 dark:divide-slate-700"
      >
        <!-- Table body -->
        <instance-table-item
          repeat.for="order of orders"
          order.bind="order"
          key.bind="order.id"
          value.bind="order.id"
        ></instance-table-item>
      </table>
    </div>
  </div>
</div>
```

```
<containerless>
<tbody class="text-sm">
</tbody>
```

 Will cause the error AUR0501, however, no slot was ever used. Any direction you can give why this is failing? Considering this as a bug right now.

Global Shadow dom is active

**Comment by bigopon** [comment] 2023-10-16 05:39
@wzrdtales thanks for the issue. This is likely because it's configured to use shadowdom globally, which means every component has shadow dom turned on by default. This causes a conflict with containerless since there's no host to attach shadow to. I guess in your case you want to disable the shadow dom for this particular component to enable containerless for it. This is tracked in #1772 
Any thoughts @3cp , maybe temporarily we can enable a way to disable shadow dom per component.

**Comment by wzrdtales** [comment] 2023-10-16 08:00
thanks for your response. I tried already deactivating it with useshadowdom(false), but it still throws the same error despite it

**Comment by wzrdtales** [comment] 2023-10-16 08:14
I added  `@useShadowDOM(false)` actually to both components, the main that includes the sub component and the subcomponent itself. Error stays unfortunately the same. Did something change and this disabling doesn't work anymore?

**Comment by wzrdtales** [comment] 2023-10-16 08:15
sorry correction @bigopon 

The error changes, to this one instead:

```
Failed to execute 'attachShadow' on 'Element': The provided value is not of type 'ShadowRootInit'.
```

**Comment by wzrdtales** [comment] 2023-10-16 08:17
Correction again, only if I apply it to the main component, if only to the subcomponent it stays AUR0501

**Comment by wzrdtales** [comment] 2023-10-16 08:19
I tried `as-element` as well which is broken with the same error `Failed to execute 'attachShadow' on 'Element': The provided value is not of type 'ShadowRootInit'.`

**Comment by wzrdtales** [comment] 2023-10-16 08:40
The only thing that yet did not throw an error, but instead the element just disappears and does not get rendered anymore was

```
@customElement({
  name: 'instance-table-item',
  containerless: true
})
```

**Comment by 3cp** [comment] 2023-10-16 09:42
In template, we have a way to optionally turn on shadow dom, or override the mode.

https://github.com/aurelia/aurelia/blob/master/packages-tooling/plugin-conventions/src/strip-meta-data.ts#L129-L135

The simplest solution would be extend that `<use-shadow-dom>` tag to add an attribute to turn it off.

**Comment by wzrdtales** [comment] 2023-10-16 09:43
But isn't this the same as `@useShadowDom(false)` which didn't work? Or does this differ?

**Comment by 3cp** [comment] 2023-10-16 09:45
I was only answering @bigopon's question about the template feature. Not sure what's the cause of this particular issue.

Yes, `@useShadowDom(false)` sounds doing the same.

**Comment by wzrdtales** [comment] 2023-10-16 10:23
ok, then yeah, this wont solve it unfortunately then. I tried that same error as stated before and even more weird errors when I go down the chain `Failed to execute 'attachShadow' on 'Element': The provided value is not of type 'ShadowRootInit'.`

**Comment by wzrdtales** [comment] 2023-10-16 19:23
I found a solution https://github.com/aurelia/aurelia/issues/1772

I just wondered, here in this issue it claims `useShadowDom(null)`, while your documentation says `false`. I just tested `null`, and with that it starts working oO

**Comment by wzrdtales** [comment] 2023-10-16 19:26
But my issue was that out of the `table` element, the container got thrown out. Even with `containerless` it still ends up outside the `table` tag.

**Comment by wzrdtales** [comment] 2023-10-16 19:30
exchanging the same with

```
<tbody
          class="text-sm"
          repeat.for="order of orders"
          order.bind="order"
          key.bind="order.id"
          value.bind="order.id"
          as-element="instance-table-item"
        ></tbody>
```

now works, so somehow aurelia seems to early output to the browser the original container name and the browser throws it out of the table structure.

**Comment by Sayan751** [comment] 2023-12-28 10:56
AFAIK, it is a known phenomenon with `<table>`. The schema of the table and what elements are permitted to be nested inside it is very tightly defined (refer to the permitted elements for `<table>` in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table)).

I am closing this for now, as it seems to me it is a not an Aurelia-issue and that a working solution is found by the OP anyway. If I am mistaken, feel free to reopen.

**Closed by Sayan751** 2023-12-28 10:56 UTC
Labels: shadow DOM
