### ISSUE TITLE
Debounce binding behavior does not work with `input.delegate` or `change.delegate`

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#786] opened 2019-12-16 00:08 UTC
# 🐛 Bug Report

Whilst attempting to use the `debounce` binding behaviour with `input.delegate` it results in an error.

## 🤔 Expected Behavior

The debounce binding behaviour should allow me to throttle my change callbacks.

## 😯 Current Behavior

The following is example code from an application I was working on. Please note, I also tried the callback function without any argument being passed and the resulting error was the same.

```
<div>
    <form>
        <div><input type="text" value.bind="address" input.delegate="addressChanged(address) & debounce:500"></div>
    </form>
</div>
```

![image](https://user-images.githubusercontent.com/368330/70871495-38445780-1feb-11ea-8bde-394365eb6e46.png)

![image](https://user-images.githubusercontent.com/368330/70871587-421a8a80-1fec-11ea-9995-b010b0b71f65.png)

Please also note that I tried this with both `input.delegate` and `change.delegate` and both produced the same error result.

## 💁 Possible Solution

My guess is that it is scoping related. Perhaps the behaviour is unable to retain the scope, so the callback cannot be found and fired off.

## 🔦 Context

I was trying to call a callback function when a user enters an address value. Because the callback is making an API request, I wanted to throttle how often it gets called.

## 💻 Code Sample

(provided in repro above)

## 🌍 Your Environment

Aurelia (latest version from Npx makes command). Latest LTS Node.js version.

**Comment by Sayan751** [comment] 2020-11-15 20:31
It seems that this particular issue is resolved, as it can be seen [here](https://stackblitz.com/edit/au2-debounce?file=my-app.html).

However, there is a odd issue involving debounce and repeat. To see that issue uncomment the following line in the demo.

```html
<!-- <div repeat.for="i of 10">${i}</div> -->
```

It seems that the issue is caused due to missing `?` here: https://github.com/aurelia/aurelia/blob/0e3b1fbe663baeb405647cd0b86231577e5cbfab/packages/runtime-html/src/resources/template-controllers/repeat.ts#L64

```diff
- if ((binding.target as { id?: number }).id === this.id && binding.targetProperty === 'items') { 
+ if ((binding.target as { id?: number })?.id === this.id && binding.targetProperty === 'items') { 
```

**Comment by fkleuver** [comment] 2021-02-01 00:57
This should be fixed now

**Closed by fkleuver** 2021-02-01 00:57 UTC
Labels: Bug, Topic: Templating
