### ISSUE TITLE
Redirect to fallback route if there's no empty route

### ISSUE THREAD

**Issue by elitastic** [aurelia/aurelia#1700] opened 2023-03-07 15:32 UTC
# 🐛 Bug Report

Redirect to fallback route is not working if there's no "empty route" (router-lite) configured.

```
getRouteConfig() {
  return {
    routes: [
      { path: 'detail', component: Detail },
      { path: 'fallback', component: Fallback },
    ],
    fallback: 'fallback',
  };
}
```

## 🤔 Expected Behavior

There should be a redirect to the fallback route if there's no `''` route configured.

## 😯 Current Behavior

There is no route loaded (au-viewport stays empty)

## 🔦 Context

I know that I could configure the `fallback` route as `''` route in this example, but this is just a simplified use case.

## 💻 Code Sample

https://stackblitz.com/edit/au2-conventions-yhgjs4

**Comment by Sayan751** [comment] 2023-03-07 21:06
What you are looking for is actually the `au-viewport[default]` value ([docs](https://docs.aurelia.io/router-lite/viewports#specify-a-default-component-for-a-viewport)). Here is a working fork of your SB project: https://stackblitz.com/edit/au2-conventions-ajxj1z?file=src/my-app.html

I am closing this, as this is not a bug. Fallback is only used when unknown routes/paths are encountered ([docs](https://docs.aurelia.io/router-lite/configuring-routes#fallback-redirecting-the-unknown-path)).

**Closed by Sayan751** 2023-03-07 21:06 UTC

**Comment by elitastic** [comment] 2023-03-08 06:37
Thank you!
