### ISSUE TITLE
Variables getting removed from production bundle

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1953] opened 2024-04-24 14:34 UTC
I found a weird issue that is causing my production builds to fail. I have noticed this since updating to `beta 15`

Here is a sample repo: https://github.com/ivanbacher/aurelia-webpack-demo

This is the structure of the sample repo:

![Screenshot 2024-04-24 at 16 26 29](https://github.com/aurelia/aurelia/assets/5493114/7cb55255-b020-4793-b7dd-0caf11f193bf)

I have a component `my-map` that loads the `mapbox-gl` lib.

if i run `npm start` everthing works as expected. However, if I run `npm run build`, the version that is in the `dist` folder will produce a strange error in the console:

```
Uncaught ReferenceError: mapbox_gl_dist_mapbox_gl is not defined
    at entry.6fb59d6853683ba9bf77.bundle.js:2:1576201
    at entry.6fb59d6853683ba9bf77.bundle.js:2:1580142
    at entry.6fb59d6853683ba9bf77.bundle.js:2:1580146
```

Inspecting the bundle:
![Screenshot 2024-04-24 at 16 29 38](https://github.com/aurelia/aurelia/assets/5493114/4721c139-aee3-4034-b462-beef0095299c)

Seems that this variable: `mapbox_gl_dist_mapbox_gl` is being removed from the bundle?

Now the weird part. If I remove the inject decorator from `my-map` and rebuild the app. Then everything is working as expected again.

Not really sure if this is an issue with webpack, aurelia, or even babel.

**Comment by ivanbacher** [comment] 2024-04-24 14:36
Maybe it has something to do with the `@babel/plugin-proposal-decorators` plugin in the `babel.config.json` file

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "loose": true,
        "modules": false,
        "exclude": [
          "@babel/plugin-proposal-dynamic-import"
        ]
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "version": "2023-11"
      }
    ],
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

**Comment by ivanbacher** [comment] 2024-04-24 19:46
I have been investigating this a bit.

Using the `@containerless` decorator causes the same issue. However using the `@customElement('my-element')` decorator does not.

I have also tried to reproduce this issue using only webpack without aurelia, but have not been able to replicate the it. 

If I had to take a guess I think it might have something to do with the `aurelia-loader` plugin?

**Comment by Sayan751** [comment] 2024-04-27 04:43
Hi @ivanbacher! I have looked into this issue briefly. It seems to me that the code are somehow being tree-shaked and not included in the bundle. You can verify this, you make the following change in the webpack configuration.

```diff
- devtool: production ? undefined : 'eval-cheap-source-map',
+ devtool: 'eval-cheap-source-map', 
```

However, I think that it has something to do with how babel is transpiling the new decorators. 

I have used ts-loader with your .js files combined with a tsconfig that allows js files, and it worked fine.

```json
//tsconfig.json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "allowJs": true,
  }
}
```

<img width="636" alt="image" src="https://github.com/aurelia/aurelia/assets/3128881/5b280fed-2419-4256-8b20-0a7b18fc937b">

**Comment by Sayan751** [comment] 2024-04-27 06:38
@ivanbacher I have looked further into this. Seems like a babel issue TBH. Opened up https://github.com/babel/babel/issues/16453 with a reproduction https://github.com/Sayan751/babel-webpack-demo.

If you take a look there, you can see that the issue can be reproduced even without the aurelia dependencies.

Closing this issue as it seems that it is not an Aurelia issue after all. Feel free to reopen if you see otherwise.

cc: @bigopon @3cp

**Closed by Sayan751** 2024-04-27 06:38 UTC

**Comment by 3cp** [comment] 2024-04-27 12:15
With my limited understanding, I think babel has nothing to do with tree shaking, it's webpack.

**Comment by Sayan751** [comment] 2024-04-27 14:48
You are right. I only suspect it is an artifact of how Babel is transpiling the code. Because it is working with ts-loader.

**Comment by 3cp** [comment] 2024-04-27 21:53
Babel guy pointed out that's terser bug. We may need to adjust webpack config for compression.

**Comment by Sayan751** [comment] 2024-04-28 06:08
Thank you @3cp for taking care of that!

**Comment by Sayan751** [comment] 2024-04-30 13:37
FYI https://github.com/terser/terser/issues/1526
