### ISSUE TITLE
router-lite: Once router error is triggered, the router does not recover

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1341] opened 2022-01-21 01:10 UTC
If, for whatever reason an error is triggered in the console, the router is never able to recover. A good example of this is the repository I created is attempting to click the "View Profile" menu item, seeing the console error and then attempting to navigate to the welcome or about page, the router does nothing and no further errors are triggered.

Furthermore, you'll notice more weird behaviour. Go to the "About" tab first, see the about page load and then click "View Profile" an error appears in the console, the URL remains the same `http://localhost:9000/about` however, it appears to have gone back to the default route as we see `Welcome to Aurelia 2!` — what should happen if a route fails is that it falls back to the prior working route (looks like maybe it attempts to do that considering the URL remains the same as the current route).

**Comment by Vheissu** [comment] 2022-09-06 06:09
Closing this as a fix appears to have been merged.

**Comment by Sayan751** [comment] 2022-09-06 15:11
@Vheissu The issue is still there for router-lite. I have renamed this and planning a fix. Keeping this assigned to myself.

**Closed** 2022-09-20 22:10 UTC
Labels: Bug, Topic: Router
