### ISSUE TITLE
Aurelia Router - Refresh issue with configured default route 

### ISSUE THREAD

**Issue by aegenet** [aurelia/aurelia#1491] opened 2022-08-05 14:06 UTC
# 🐛 Bug Report

With `@aurelia/router`, if we have specified a default route per configured route (`{ path: ['', '/home'] }`), the default route will only appear the first time. `F5`, refresh, and the page disappears.

[Aurelia 2 doc, specify routes](https://docs.aurelia.io/developer-guides/routing/creating-routes#specify-routes)

## 🤔 Expected Behavior

Just refresh and display the default route.

## 😯 Current Behavior

The default route disappear on F5.

## 💁 Possible Solution

If we specify the name of the component in the `default` attribute of `au-viewport`, the default route works as expected.

But the configured route is not used and we are forced to load the component (i.e. no lazy-load), even if the home page is not displayed.

In `my-app.html`:

```diff
++<import from="./pages/home-page"></import>

-- <a load="/">Home</a> 
++  <a href="/">Home</a>

-- <au-viewport name="main"  fallback="missing-page"></au-viewport>
++ <au-viewport name="main" default="home-page" fallback="missing-page"></au-viewport>

```

In `my-app.ts`:
```diff
-- path: ["", "home"],
++ path: ["home"],
```

## 🔦 Context

I am using @aurelia/router with configured routes.
I want to load the routes lazily.

## 💻 Code Sample

Here: [Project](https://gist.dumber.app/?gist=34ca8e1c17beaeda594e4a673bd78554)

>⚠️ If you want to "see" the bug with this project, just inspect the preview and open the iframe url in a new tab, then refresh.
> _i.e. https://[xxxx].gist.dumber.app/_

1. Open the home page _https://[xxxx].gist.dumber.app/_ in a new tab.
2. Refresh the page with F5.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.37
| Language         | TypeScript
| Browser          | Chrome 104.0.5112.81, Firefox 103.0.1
| Bundler          | Dumber / Webpack
| Operating System | Windows 11
| NPM/Node/Yarn    |

**Comment by Vheissu** [comment] 2022-08-05 14:24
Thank you for this. I can confirm we are seeing the same behaviour and a fix for this should be out soon.

**Comment by jwx** [comment] 2022-08-19 23:08
The fix is in (https://github.com/aurelia/aurelia/pull/1501) and will be in the next release.

**Comment by aegenet** [comment] 2022-09-07 13:26
Hello, this does not seem to be fixed in the alpha.40 version:

https://gist.dumber.app/?gist=afe2f6edb7b87e92730bf422a76caba4

You can reproduce the issue as I indicated above.

(I also tested with a project using webpack)

**Comment by jwx** [comment] 2022-09-08 15:27
@aegenet Can you elaborate on this because I'm not seeing any issues in the gist you linked above.

**Comment by aegenet** [comment] 2022-09-08 15:33
> ⚠️ If you want to "see" the bug with this project, just inspect the preview and open the iframe url in a new tab, then refresh.
> i.e. https://[xxxx].gist.dumber.app/
> 

![image](https://user-images.githubusercontent.com/20248096/189163227-63bf5645-c193-4be6-8fcd-cb3cf1a1df57.png)

Open in a new tab, refresh and you can see the issue.

Thank you, I trust your project ;-)

**Comment by jwx** [comment] 2022-09-09 11:28
@aegenet The test I had didn't cover your use case. I've created a new PR. Sorry for the trouble.

**Closed** 2022-09-09 11:53 UTC
Labels: Bug
